### ISSUE TITLE
//root/p[@attr='val'] is not working

### ISSUE THREAD

**Issue by mildred** [antchfx/xpath#10]
I have the following example document:

```
<?xml version="1.0"?>
<root>
	<foo>
		<bar a="b"/>
	</foo>
	<li>
		<a class="tag" href=""/>
	</li>
	<p class='meta'>
	</p>
</root>
```

with the following xpath expression: `//root/p[@class='meta']`

The expression does not find the `<p/>` node while the [XPath tester](https://www.freeformatter.com/xpath-tester.html) can.

**Comment by mildred** [comment]
It seems caused by the `childQuery` not checking the predicate on its Input directly and wanting to iterate to children before. I believe this change should fix the issue:

```diff
diff --git a/query.go b/query.go
index fe2633f..d3ef543 100644
--- a/query.go
+++ b/query.go
@@ -198,6 +198,9 @@ func (c *childQuery) Select(t iterator) NodeNavigator {
                        node = node.Copy()
                        first := true
                        c.iterator = func() NodeNavigator {
+                               if c.Predicate(node) {
+                                       return node
+                               }
                                for {
                                        if first {
						if !node.MoveToChild() {

```

**Comment by mildred** [comment]
Perhaps there are legitimate cases where we want to check for children and not the current node, but `//` means `/descendant-or-self::node()/` ([section 2.5 of W3C XPath 1.0 recommendation](https://www.w3.org/TR/xpath/#path-abbrev))

**Comment by mildred** [comment]
The above patch is creating an infinite loop somewhere in the tests, It should probably be tweaked to behave like this only in some cases.

**Comment by zhengchun** [comment]
Looks generate XPath query for XPath expression problem.

default generate query look is : `filterQuery` > `childQuery` > `childQuery`  > `descendantQuery` but it should be like this: `filterQuery` > `childQuery` > `descendantQuery`.
