### ISSUE TITLE
./rootElem doesn't select root element node

### ISSUE THREAD

**Issue by mildred** [antchfx/xpath#11]
Hi,

I have an issue with the xpath library, when I use `./rootElem` on the following document:

```
<rootElem>
  foobar
</rootElem>
```

I expect XPath to select the root element, but instead I get nothing. When looking at [FreeFormatter XPath processor](https://www.freeformatter.com/xpath-tester.html) with this use case, I have a non empty result.

I think I could debug this back to the axis predicate function. In build.go:

https://github.com/antchfx/xpath/blob/b4b6b7435adca249482b4d80dc87f0510d89e288/build.go#L40-L47

While evaluating the contextQuery, the condition `typ == n.NodeType() || typ == TextNode ` is false because the expected type, `typ` is `ElementNode` (1) while `n.NodeType()` is a `RootNode` (0). The trick here is that the root node is technically an element too, and it shouldn't be treated differently.

The context query ends up not selecting anything from the document and the rest of the xpath evaluation cannot take place.

I have a test case ready here:

https://github.com/mildred/xpath/blob/8981e96e9308941d21c4ce252753a77bb8b9f105/test/xquerytest.go#L142-L147

**Comment by zhengchun** [comment]
You are right. `RootNode` type should be as `ElementNode` to compare.

**Comment by mildred** [comment]
To be more precise, the root node must not always match when we look for an element node. The RootNode corresponds to the Document object.

In case of selfQuery, we want to match the context, the predicate is always true. #12 should fix this issue.
