### ISSUE TITLE
child::node() is not selecting text nodes

### ISSUE THREAD

**Issue by mildred** [antchfx/xpath#13]
Given the following document:

```
<root>
<para> text <img/> text </para>
</root>
```

Given the context node selected by `//para`

When selecting child nodes using `./child::node()`

Then, only the `<img/>` node is selected instead of all three nodes including the two text nodes. I believe this is a similar issue to #11: the default predicate for all queries is to select only element nodes.

**Comment by mildred** [comment]
Perhaps I'm wrong here, depending on the branch I use I cannot always reproduce that.

**Comment by mildred** [comment]
I could reproduce every time with the test case included in #8

**Comment by zhengchun** [comment]
@mildred ,I'm add new NodeType: `AllNode` that can solve about `self`,`parent`,`node()` predicate. 239293479a6c474e16fd237996192d4da197dca6

**Comment by mildred** [comment]
Ok.

Even though I like a lot functions as first class values, I prefer that predicates are objects and not functions. See PR #14. Objects can easily be printed via their `String()` method and these log messages help me immensly to see what's going wrong. So I'm going to keep it in my fork.

Also, I don't know if the NodeNavigator interface should be bothered with an AllNode constant. That's completely outside of the NodeNavigator interface and DOM implementations that implements it have no business with AllNode. That's purely a thing to live in the xpath package only. Perhaps what would be interesting would be to have node types be power of two, and AllNode a constant that is the binary union of all the types. That makes more sense.

**Comment by zhengchun** [comment]
In the beginning of the project, i'm still use predicate function as field of query object because i don't want create `matches(NodeNavigator)` method for each query. 

```go
predicate := func(n NodeNavigator) bool {
    if typ == n.NodeType() || typ == allNode || typ == TextNode {
        if root.LocalName == "" || (root.LocalName == n.LocalName() && root.Prefix == n.Prefix()) {
            return true
        }
    }
    return false
}
```
predicate method can simplify following:

```go
predicate := func(n NodeNavigator) bool {
    return typ==n.NodeType() || typ == allNode || typ == TextNode && (root.LocalName == "" || (root.LocalName == n.LocalName() && root.Prefix == n.Prefix()))
}
```
It is the overall and can't split to multiple predicates.
