### ISSUE TITLE
xpath with count does not return anything

### ISSUE THREAD

**Issue by pjvw1995** [antchfx/xpath#16]
Usecase: http://xpather.com/Kp2lY28A

I am using a xpath to select all `p` elements containing `sup` elements between tables. 
```
for i := 1; i < 10; i++ {
	xp := fmt.Sprintf("//table[%v]/following-sibling::p[child::sup][count(.|//table[%v]/preceding-sibling::p[child::sup])=count(//table[%v]/preceding-sibling::p[child::sup])]", i, i+1, i+1)
	expr, err := xpath.Compile(xp)
	if err != nil {
		logger.Log.Error(err)
		return nil, "", err
	}
	iter := expr.Evaluate(htmlquery.CreateXPathNavigator(dc)).(*xpath.NodeIterator)
	for iter.MoveNext() {
		logger.Log.Debug(iter.Current().Value())
	}
}
```
The final xpath is `//table[1]/following-sibling::p[child::sup][count(.|//table[2]/preceding-sibling::p[child::sup])=count(//table[2]/preceding-sibling::p[child::sup])]`. When I test this xpath in the usecase it returns the correct values. Am I using a xpath which isn't supported or is it a bug somewhere in this library?

**Comment by zhengchun** [comment]
Thanks for report, it looks like a bug. i will test this XPath.

**Comment by zhengchun** [comment]
@pjvw1995 , I have a question, the `//table[1]/following-sibling::p[child::sup][count(.|//table[2]/preceding-sibling::p[child::sup])`'s `count` what is value return?  is `1` or `3` or `5`?

**Comment by pjvw1995** [comment]
@zhengchun This xpath selects all `p-elements` between two tables which contains a `sup` element. So the expected value here are the **3** `p-elements`.

**Comment by zhengchun** [comment]
@pjvw1995 , trying again. A `|` symbol as union operator expr, not as `or` operator.
