### ISSUE TITLE
Node Attribute Selection Not Working per Specification

### ISSUE THREAD

**Issue by MrWinstead** [antchfx/xpath#17]
# Example XML
```xml
<message>
  <from>sendUser@example.com</from>
  <to>destUser@example.com</to>
  <body ctime="1 January 1980">
    Isn't XPATH awsome?
  </body>
</message>
```

# Example XPATH

```/message/body/@ctime```

# Current Behavior

The xpath library will return the ```<body>``` node rather than the ```ctime``` attribute of the node.

# Expected Behavior

```bash
$ cat example.xml
<message>
  <from>sendUser@example.com</from>
  <to>destUser@example.com</to>
  <body ctime="1 January 1980">
    Isn't XPATH awsome?
  </body>
</message>
$ xmllint --version
xmllint: using libxml version 20903
   compiled with: Threads Tree Output Push Reader Patterns Writer SAXv1 FTP HTTP DTDValid HTML Legacy C14N Catalog XPath XPointer XInclude Iconv ISO8859X Unicode Regexps Automata Expr Schemas Schematron Modules Debug Zlib Lzma
$ xmllint --xpath "/message/body/@ctime" ./example.xml 
ctime="1 January 1980"
```

I also believe that this should be the behavior after reading [XPATH 3.0](https://www.w3.org/TR/2014/REC-xpath-30-20140408/) wherein it states:

> Here are some examples of path expressions that use the abbreviated syntax:
> * ```para``` selects the para element children of the context node
> * ```*``` selects all element children of the context node
> * ```text()``` selects all text node children of the context node
> * ```@name``` selects the name attribute of the context node

# Resolution

I'm currently working on my fork of this repo to produce a test which will specifically support node attribute selection

**Comment by MrWinstead** [comment]
This behavior was observed using the [xmlquery](https://github.com/antchfx/xmlquery) package.

After a few hours of spelunking, it appears that the issue may be in different ```NodeNavigator``` implementations used between ```xmlquery``` and the test suite of ```xmlpath``.

**Comment by zhengchun** [comment]
@MrWinstead , Thanks for report it.  It looks similar to issue https://github.com/antchfx/xpath/issues/4. You need implement `NodeNavigator` interface or using the [xmlquery](https://github.com/antchfx/xmlquery) package.

```go
expr, _ := xpath.Compile("/message/body/@ctime")
val := expr.Evaluate(xmlquery.CreateXPathNavigator(doc))
switch typ := val.(type) {
case *xpath.NodeIterator:
	for typ.MoveNext() {
		fmt.Println(typ.Current().Value()) // output @src value
	}
}
```

I hope it can help you, if you still have question, please tell me.

**Comment by zhengchun** [comment]
@MrWinstead, Sorry i'm late, I am trying solving this problem, can you checkout this branch [xpath_#17](https://github.com/antchfx/xmlquery/tree/xpath_%2317) of `xmlquery` and https://github.com/antchfx/xmlquery/issues/3.
