### ISSUE TITLE
Function substring returns boolean

### ISSUE THREAD

**Issue by lazize** [antchfx/xpath#20]
If we use the test condition below it will panic.
It panics because in this case `substring` returns `false (boolen)`, so when it try to compare `false = ''` it fails.
If we remove the compare condition it works fine, but should `substring` work as boolen condition?

Panic:
`testXPath2(t, html, "//title[substring(child::*,0) = '']", 0)`

Work:
`testXPath2(t, html, "//title[substring(child::*,0)]", 0)`

**Comment by zhengchun** [comment]
its a bug,`substring` should return an empty string, not a false.

**Comment by lazize** [comment]
Maybe it worth to put the return value of each function in `README.md`, like:

    * starts-with( string, string ) string
    * ends-with( string, string ) string
    * normalize-space( string ) string
    * substring( string , start : int [, length : int] ) string
    * string-length( [string] ) string
    * contains( string, string ) boolean
    * sum( node-set ) int64

**Comment by zhengchun** [comment]
Very good.

the `sum()` return value type is `float64`.

**Comment by lazize** [comment]
Should it has `float64` or just `int` or `number`?
Because the precision here doe not matter so much as we use it inside xpath string.

What do you think?

**Comment by lazize** [comment]
Like this:

```
    * position() number
    * last() number
    * count( node-set ) number
    * name() string
    * starts-with( string, string ) boolean
    * ends-with( string, string ) boolean
    * normalize-space( string ) string
    * substring( string , start : number [, length : number] ) string
    * not( expression ) boolean
    * string-length( [string] ) number
    * contains( string, string ) boolean
    * sum( node-set ) number
    * concat( string1 , string2 [, stringn]* ) string
```

**Comment by zhengchun** [comment]
consider a `sum(1+1.2)`, it return a float number, or `sum(count(//a)+2.0)` etc. 

Another reason is Golang no number type and can not perform an expression like this : `int + float`, `float64` can compatibility `int`,  So for simplify, `float64` as default type, even `position()` or `count()` function.
