### ISSUE TITLE
feature: Support exists()

### ISSUE THREAD

**Issue by PintoKrysler** [antchfx/xpath#27]
Could you add support for exists() func?

I would like to create a condition using`exists`, something like this:

/SpliceInfoSection/SegmentationDescriptor[not(exists(DeliveryRestrictions))]

**Comment by zhengchun** [comment]
Hi, this looks similar is `boolean()` function.  trying the following expp ,but not sure whether can work,
`/SpliceInfoSection/SegmentationDescriptor[boolean(DeliveryRestrictions)=false]`
`/SpliceInfoSection/SegmentationDescriptor[not(boolean(DeliveryRestrictions))]`

**Comment by PintoKrysler** [comment]
this worked  /SpliceInfoSection/SegmentationDescriptor[not(boolean(DeliveryRestrictions))]. 

Thank you!
