### ISSUE TITLE
xmlquery:   Can I have from node.OutputXML() elements with prefix

### ISSUE THREAD

**Issue by dundich** [antchfx/xpath#31]
```
t.Run("Xml", func(t *testing.T) {
doc, _ := xmlquery.Parse(strings.NewReader(`<soapenv:Envelope 
xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tem="http://tempuri.org/">
   <soapenv:Header/>
   <soapenv:Body>
      <tem:GetOtpuskTovarov>
         <tem:_dateFrom>?</tem:_dateFrom>
         <tem:_dateTo>?</tem:_dateTo>
      </tem:GetOtpuskTovarov>
   </soapenv:Body>
</soapenv:Envelope>
  `))
  fmt.Println(doc.OutputXML(false))
   if strings.Index(doc.OutputXML(false), "<tem:_dateFrom>") < 0 {
	t.Error("OutputXML")
		return
	}
  })
```
stdout:
`<?xml?><Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tem="http://tempuri.org/"><Header></Header><Body><GetOtpuskTovarov><_dateFrom>!!!</_dateFrom><_dateTo>?</_dateTo></GetOtpuskTovarov></Body></Envelope>`

**Comment by zhengchun** [comment]
what is the version of `xmlquery`? I remember have fixed this issue https://github.com/antchfx/xmlquery/commit/94382708863c7d6e69cf016943668d6ef733fbb7, you should  to go get latest version of `xmlquery`.

**Comment by dundich** [comment]
You're right   ...there was an old version ~ github.com/antchfx/xquery/xml   I'm sorry...
