### ISSUE TITLE
preceding-sibling::[n] returns incorrect value for n > 1 

### ISSUE THREAD

**Issue by vibhavp** [antchfx/xpath#39]
Using [xmlquery](https://github.com/antchfx/xmlquery), the following program outputs `preceding-sibling::*[2] not found`, even though both the XPath expressions are correct, and should evaluate to node `b` and `c` respectively:

```golang
package main

import "strings"
import "github.com/antchfx/xmlquery"

func main() {
	doc, _ := xmlquery.Parse(strings.NewReader(`<root>
<a>
<b id="b"></b>
<c id="c"></c>
<d id="d"></d>
</a>
</root>`))

	if node := xmlquery.FindOne(doc, `//*[@id="d"]/preceding-sibling::*[2]`); node == nil {
		println("preceding-sibling::*[2] not found")
	}

	if node := xmlquery.FindOne(doc, `//*[@id="d"]/preceding-sibling::*[1]`); node == nil {
		println("preceding-sibling::*[1] not found")
	}
}
```

Maybe related to https://github.com/antchfx/xpath/issues/36?

**Comment by zhengchun** [comment]
hello, @vibhavp , This bug as same as https://github.com/antchfx/xmlquery/issues/14, add `position()` to the `precedingQuery` struct.

**Comment by vibhavp** [comment]
@zhengchun Thanks for the quick reply! However, I did try building this with the latest `xpath` repo, and the problem persists.

**Comment by zhengchun** [comment]
you mean is a  `preceding-sibling::[n]` not return correct value or package build error?

the `preceding-sibling::[n]` bug is not fix yet.

**Comment by zhengchun** [comment]
@vibhavp , Check out the latest commit code, It tested and can work on my code.

**Comment by vibhavp** [comment]
Ah, okay.
