### ISSUE TITLE
How to concatenate?

### ISSUE THREAD

**Issue by vtolstov** [antchfx/xpath#41]
I need to concat two fields from xml  and return them combined

**Comment by vtolstov** [comment]
i have simple xml
```
  <SYSTEM>
    <concat1 Value="test1"/>
    <concat2 Value="test2"/>    
  </SYSTEM>
```

i need to select concatenation of concat1 value attribute with concat2 value attribute

**Comment by vtolstov** [comment]
concat(/SYSTEM/concat1@Value/text(), " ", /SYSTEM/concat2@Value/text()) 
does not works: has an invalid token

**Comment by vtolstov** [comment]
concat(//SYSTEM/concat1[@Value]/text(), " ", //SYSTEM/concat2[@Value]/text())
this not returns only " "

**Comment by vtolstov** [comment]
only this works 
concat(//SYSTEM/concat1/@Value, " ", //SYSTEM/concat2/@Value)

**Comment by vtolstov** [comment]
does this behaviour expected? i don't see such syntax via googling

**Comment by zhengchun** [comment]
`concat(//SYSTEM/concat1/@value, " ", //SYSTEM/concat2/@value)` is a correct syntax.

**Comment by vtolstov** [comment]
ok,thanks
