### ISSUE TITLE
Infinite loop with specific selector

### ISSUE THREAD

**Issue by olivier-m** [antchfx/xpath#48]
Hi, thanks for your library. It works very well, except for a bug I found.
With the selector `(//p//time//ancestor::p[1])[starts-with(normalize-space(.), 'Published on ')]` the CPU and memory go to the roof. There's likely an infinite loop somewhere. I've been trying to find a fix but couldn't manage.
Here's a file to reproduce the issue.
[xpath.txt](https://github.com/antchfx/xpath/files/4622660/xpath.txt)

**Comment by zhengchun** [comment]
fixed in v1.1.8(https://github.com/antchfx/xpath/releases/tag/v1.1.8)

**Comment by olivier-m** [comment]
Splendid! Thanks :slightly_smiling_face:
