### ISSUE TITLE
xpath error

### ISSUE THREAD

**Issue by 474420502** [antchfx/xpath#52]
(//span[@class='tw-user-nav-list-count']/text())[2]  xpath. the result is null. 
chrome check it. result is exist.
[test.zip](https://github.com/antchfx/xpath/files/5089228/test.zip)

**Comment by zhengchun** [comment]
change to `//span[@class='tw-user-nav-list-count'][2]/text()`

`text()` function will return text node on the `antch's xpath` library. you should return `Node` object and then call `text()`.

By the way, I found your xpath expression had a problem:  [`@Class='tw-user-nav-list-count']`. You should change **Class=''** to the lower-letters  **class=''**, XPath library is case sensitivity for the query expression, your HTML page uses **class** letter not **Class**.

**Comment by 474420502** [comment]
Class is auto transformed by System!
I know how to correct it. 
I only tell you that is different to chrome xpath.
 
![image](https://user-images.githubusercontent.com/9397764/90500612-b90cb200-e17d-11ea-8a00-a2269b20b6bf.png)

I think the logic implemented by xpath is not perfect.

**Comment by zhengchun** [comment]
Okay, I got that what your mean. I flag this.
