### ISSUE TITLE
position() increments by 2

### ISSUE THREAD

**Issue by srebhan** [antchfx/xpath#53]
Hey,

when running this code:
```golang
package main

import (
        "fmt"
        "strings"

        "github.com/antchfx/xpath"
        "github.com/antchfx/xmlquery"
)

func main(){
        xml := `
<?xml version="1.0"?>
<Indices>
  <Index>
    <Name>1</Name>
    <Data>
      <Value>0</Value>
      <Value>1</Value>
      <Value>2</Value>
      <Value>3</Value>
      <Value>4</Value>
      <Value>5</Value>
      <Value>6</Value>
    </Data>
  </Index>
</Indices>
        `

        // Parse the XML
        doc, err := xmlquery.Parse(strings.NewReader(xml))
        if err != nil {
                panic(err)
        }

        // Queries
        selected, err := xmlquery.QueryAll(doc, "//Data/child::Value")
        if err != nil {
                panic(err)
        }
        if len(selected) > 0 && selected[0] != nil {
                for i, context := range selected {
                        expr, err := xpath.Compile("position()")
                        if err != nil {
                                panic(err)
                        }
                        r := expr.Evaluate(xmlquery.CreateXPathNavigator(context))
                        fmt.Printf("[%02d] result: %v (%T)\n", i, r, r)
                }
        }
}
```

I get the following output
```
[00] result: 2 (float64)
[01] result: 4 (float64)
[02] result: 6 (float64)
[03] result: 8 (float64)
[04] result: 10 (float64)
[05] result: 12 (float64)
[06] result: 14 (float64)
```
where the expected position output is 1, 2, ..., 7...

What am I doing wrong here?

**Comment by zhengchun** [comment]
Your code is OK. The problem was occurred at https://github.com/antchfx/xpath/blob/0875c036385f866045f44b15be381167fc2295b4/func.go#L40

at `for node.MoveToPrevious() {`, if the current node had a previous node(previous node is empty node \r\n), `count+1`, that is why you call `position()` increment by `2`. 

if you xml change to the following:

```xml
    <Data><Value>0</Value><Value>1</Value><Value>2</Value><Value>3</Value><Value>4</Value><Value>5</Value><Value>6</Value>
    </Data>
```

your code will run ok. I need some time to think about whether should ignore empty node .

**Comment by srebhan** [comment]
If possible, can we add an explicit flag (e.g. `ignore_whitespace_cdata` or similar) to ignore those empty nodes? Alternatively, it would be nice to have a helper function removing such empty/whitespace-only nodes when parsing...

**Comment by zhengchun** [comment]
https://github.com/antchfx/xmlquery/commit/efaedac7222ad733b3c53c090e55d0d64c2a7e38 

Check the latest committed code on `xmlquery` package that have to ignore these empty text nodes , closed.
