### ISSUE TITLE
Turning xpath into dom manipulation tool as well

### ISSUE THREAD

**Issue by suntong** [antchfx/xpath#62]
I know it sounds odd at first but please hear me out. 

I've been searching for an XML-2.0-compatible Go based XML manipulation tool/lib for a long long time, and I believe there is no such tool/lib exist. I can go on and on about the tools that I looked into before, but please do let me know if I'm wrong, that there is indeed such Go based XML manipulation tool/lib out there, which can satisfy the following simple requirements,

- locate XML node with XPath 1.0/2.0 query
- do basic xml node manipulation like, add/delete/change attribute, create/insert/append/delete ChildNode, etc

I saw that this `xpath` package already has functions like `addAttribute`, `createChildNode`, so the first step making xpath into a dom manipulation tool is simple, just expose those ready-made functions as public, and adding the missing functionalities would be step 2. 

What would you say?

**Comment by zhengchun** [comment]
How about [xmlquery](https://github.com/antchfx/xmlquery) and [htmlquery](https://github.com/antchfx/htmlquery)? this `xpath` package only works for XPath not provides DOM manipulate.

https://github.com/antchfx/xmlquery/pull/38

https://pkg.go.dev/golang.org/x/net/html#Node

**Comment by suntong** [comment]
I don't quite understand what you are suggestion here. Maybe you can try explaining in Chinese? I understand that there is a similar request at antchfx/xmlquery#38. So,

Can we at least Expose the following *Node related helper functions first pls?
https://github.com/antchfx/xpath/blob/cd2afb821d43992abcefe1c70b1b41af5b640179/xpath_test.go#L654-L659

If there are other helper functions, like `AddAttr`, `AddChild`, `AddSibling`, `RemoveFromTree`. Would it be OK to expose them as well?

**Comment by suntong** [comment]
They said that XPath 1.0 is only focus on selection, but XPath 2.0's focus has been shifted to XML manipulation. I may have not express it well, I don't need dom manipulation, I only need functions like `AddAttr`, `AddChild`, `AddSibling`, `RemoveFromTree`, giving the located xpath node.

**Comment by zhengchun** [comment]
Sorry for I didn't make it clear.

 `XPath` is a  document query package, it helps you easy find some matched in your document like HTML, XML, JSON and other document and don't need understand your DOM package.  In `htmlquery` and `xmlquery` and `jsonquery` they are all implemented `NodeNavigator` interface, that means you can create owned DOM and supports XPATH query. 

for example, you have a HTML document. when you get the returned HTML node, you can also do some other operations in your DOM package: AddAttribute, AppendChild, 

for example:

```go
node:= htmlquery.FindOne(doc,"//div")
node.AddAttribute("class","link") // in here, we assume HTML node have a AddAttribute() method.
node2:= htmlquery.FindOne(doc,"//div[@class='link']"
```

`createChildNode` and `addAttribute` in the `xpath_test.go` file are just convenient for testing.

**Comment by suntong** [comment]
Ah, make sense. thx!
