### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by dataf3l** [antchfx/xpath#71]
HI friends, thank you for building this project, I am not very familiar with XPATH, and have a small question

if I have a node that looks like this:
```
<books>
  <book>   book name.  </book>
</books>
```

and I ask for this expression:

```
//books/book
```

then, is there a way for the xpath to return the normalize-string()'d version of the book name?
as in, replace "   book name.  " and return only "book name." without any trailing or leading spaces?
is that even possible with xpath.

**Comment by zhengchun** [comment]
No, you should called `strings.TrimSpace()` when getting XML node, like this `strings.TrimSpace(n.InnerText())`

**Comment by dataf3l** [comment]
thank you @zhengchun for your time :) your suggestion solved our problem
