### ISSUE TITLE
Discussion: Provide `NodeNavigator` interface to get native data

### ISSUE THREAD

**Issue by srebhan** [antchfx/xpath#77]
When using the xpath library with data-formats that _know_ the data-type of a node (e.g. [JSON](https://github.com/antchfx/jsonquery) or [Protocol buffer](https://github.com/DocLambda/protobufquery) it would be nice to have access to this native underlying value. This has the benefit of being able to parse data with unknown a-priori format and/or data-types.

The above can be done by adding an interface
```golang
type NodeNavigatorNativeData interface {
	// NativeValue gets the native value of current node.
	NativeValue() interface{}
}
```
or, alternatively, change the return type of `Value()` in the `NodeNavigator` interface. The naming is subject to discussion.

Please let me know what you think and I can submit a PR for either way.

**Comment by zhengchun** [comment]
Sorry, don't fully understand, You mean xpath directly access native value without the  third-party package that  implemented xpath?

Please provides your use case how implemented or pseudo code. 

If my understand is correct, you mean provides a new feature like for `NodeNavigator `, like this，

```
// xpath
class NodeNavigator<T> {
  function Value() T
}

// xmlquery
class XmlNodeNavigator: NodeNavigator<XmlNode>{
 function Value() XmlNode
}
```

right?

**Comment by srebhan** [comment]
Sorry for the late reply. Let me explain my use case... Imaging you do have a JSON document
```json
{
  "a": "a string",
  "b": 3.1415,
  "c": true
}
```
and the following code
```golang
package main

import (
  "fmt"
  "os"

  "github.com/antchfx/xpath"
  "github.com/antchfx/jsonquery"
)


func main() {
  filename := "test.json"
  queries := []string{"//a", "//b", "//c"}

  f, err := os.Open(filename)
  if err != nil {
    panic(fmt.Errorf("failed to read file %q: %w", filename, err))
  }
  defer f.Close()

  doc, err := jsonquery.Parse(f)
	if err != nil {
    panic(fmt.Errorf("failed to parse document: %w", err))
	}

	// Queries
  for _, query := range queries {
    // Compile the query expression
    expr, err := xpath.Compile(query)
    if err != nil {
      panic(fmt.Errorf("failed to compile query '%s': %v", query, err))
    }

    // Evaluate the compiled expression
    var r interface{}
    node := expr.Evaluate(jsonquery.CreateXPathNavigator(doc))
    if iter, ok := node.(*xpath.NodeIterator); ok {
      if iter.MoveNext() {
        r = iter.Current().Value()
      }
    }
    fmt.Printf("query %q: %v (%T)\n", query, r, r)
  }
}
```

Currently, this will print
```text
query "//a": a string (string)
query "//b": 3.1415 (string)
query "//c": true (string)
```

However, as a JSON document _knows_ the types of the data in its nodes, I would like to get the following output
```text
query "//a": a string (string)
query "//b": 3.1415 (float64)
query "//c": true (bool)
```

This could be done by changing the interface of `NodeNavigator` from `Value() string` to `Value() interface{}` or by adding an additional interface as described above. Of course this would mean to also adapt `jsonquery` etc...

**Comment by zhengchun** [comment]
I get it. Xpath accepts string as source and only return string type for query. only change `NodeNavigator.Value() string` to `NodeNavigator.Value() interface{}` is does't make sense, you still need parse string value to int, book and float in `NodeNavigator.Value() interface{}` method.

The best way is to create the extension methods like `ToInt()` , `ToBool()` for `NodeNavigator` interface.

**Comment by srebhan** [comment]
@zhengchun let me know what you think. Maybe I can even spend some time on a PR if it is clear how to tackle the situation...

**Comment by zhengchun** [comment]
Hello, I'm here, sorry for later. I knowed what you means now.

Your suggest is right, the `xpath.NodeNavigator` is as an inteface{} only used by `xpath` package for querying any structured documents like HTML, XML, JSON etc.  So we just keeping `Node.Data` as tag name used by xpath query and save value on the anoter fileld, This will not affect the xpath package.

https://github.com/zhengchun/jsonquery2/blob/795bb676938e644ffa67c905dde0a2f164748c36/node.go#L160

```go
type Node struct {
  Data string // Keeping this as a tag name, used by xpath for query tag.

  value interface{}
}

func (n *Node) Value() interface{} {
	return n.value
}
```

I take some times creating a demo project for JSON on https://github.com/zhengchun/jsonquery2

```go
func Example_1() {
 s := `{
  "large_number": 365823929453
}`
  doc, _ := jsonquery.Parse(strings.NewReader(s))
  n := doc.SelectElement("large_number")
  fmt.Println(n.Value().(float64) == float64(365823929453))
}
```

full example code at https://github.com/zhengchun/jsonquery2/blob/master/example.go

If you decide this is a good idea, we can improved it and merge it.

**Comment by srebhan** [comment]
Thanks for the quick feedback! I think it's a good idea and I did something similar in my implementation of [protobufquery](https://github.com/DocLambda/protobufquery/blob/master/node.go). (Btw: If you want to take that package I will be super happy!) So yes, let's do it.

**Comment by zhengchun** [comment]
Sure, If you agree, you can submit a PR add [protobufquery](https://github.com/DocLambda/protobufquery) to the list of implementations.

**Comment by srebhan** [comment]
@zhengchun I thought you maybe can fork the repo and I will deprecate/archive my location and point users to your repo... This way all `*query` packages would be in one location...

**Comment by srebhan** [comment]
Hey @zhengchun, I finally found the time to test your change and it works as expected. Thank you!

Can we also provide the `GetValue()` interface for the `xpath` NodeNavigator so I can get rid of the type assertions?
