### ISSUE TITLE
The multiple filter query with last() and concat() function

### ISSUE THREAD

**Issue by Fedorov688** [antchfx/xpath#89]
```xml
<root name="group1">
    <child name="child1">
    <test foo="bar" value="1">First</test>
    <test foo="bar" value="2">Second</test>
    <test foo="xyz" value="3">Third</test>
    </child>
</root>
```

## Test

```
concat(
(//root[@name="group1"]/child[@name="child1"]/test[@foo="bar"]/@value)[last()],
"-",
(//root[@name="group1"]/child[@name="child1"]/test[@foo="xyz"]/@value)[last()]
)
```

In version:
	github.com/antchfx/xmlquery v1.3.12
	github.com/antchfx/xpath v1.2.1

actually:

`1-`

In version:
	github.com/antchfx/xmlquery v1.3.15
	github.com/antchfx/xpath v1.2.3

actually:

`-`

expected:

`2-3`

**Comment by Fedorov688** [comment]
@zhengchun #76 #78

**Comment by zhengchun** [comment]
changes `concat((//root[@name="group1"]/child[@name="child1"]/test[@foo="bar"])[last()]/@value,"-",(//root[@name="group1"]/child[@name="child1"]/test[@foo="xyz"])[last()]/@value	)`  works.

`last()` only works for the `Node set`, not for string value.

**Comment by Fedorov688** [comment]
> 

Thanks for quick answer!

Last() used for array, not for string, example:

```
(//root[@name="group1"]/child[@name="child1"]/test[@foo="bar"]/@value)
```
expected return:
```
1
2
```

And 

```
(//root[@name="group1"]/child[@name="child1"]/test[@foo="bar"]/@value)[last()]
```
expected return:
```
2
```

In many Online Xpath Testers  both examples:
```
concat(
(//root[@name="group1"]/child[@name="child1"]/test[@foo="bar"]/@value)[last()],
"-",
(//root[@name="group1"]/child[@name="child1"]/test[@foo="xyz"]/@value)[last()]
)
```
And
```
concat((//root[@name="group1"]/child[@name="child1"]/test[@foo="bar"])[last()]/@value,"-",(//root[@name="group1"]/child[@name="child1"]/test[@foo="xyz"])[last()]/@value	)
```
Worked correctly.



Your example Works with updated to:

```
	github.com/antchfx/xmlquery v1.3.15
	github.com/antchfx/xpath v1.2.4
```


Thanks for help!
