### ISSUE TITLE
xpath /foo/bar@attr doesn't match the attribute node but the bar element

### ISSUE THREAD

**Issue by mildred** [antchfx/xpath#9]
In the following document:

```
<?xml version="1.0"?>
<root>
	<foo>
		<bar attr="b"/>
	</foo>
</root>
```

the xpath expression `/foo/bar@attr` matches `<bar/>` instead of `attr="b"`

Test case in https://github.com/antchfx/xpath/pull/8 instantiated in https://github.com/antchfx/xquery/pull/19

**Comment by zhengchun** [comment]
@mildred , Sorry for the late reply .

I don't thought this is a bug.  `/foo/bar@attr` expression means `searchs bar element with attr attribute`.
xpath package matches node and return it, even you are specified attribute conditions. 

The package `Expr` have two methods: `Seelct` and `Evaluate`. if you want matches `attr="b"`, you can invoke `Evaluate` method. https://github.com/antchfx/xpath/issues/4#issuecomment-306989779

```go
expr, err := xpath.Compile("//img/@src")
val := expr.Evaluate(nav)
switch typ := val.(type) {
case *xpath.NodeIterator:
    for typ.MoveNext() {
	fmt.Println(typ.Current().Value()) // output @src value
    }
}
```

**Comment by mildred** [comment]
Thank you, but the test I made [here](https://github.com/antchfx/xpath/pull/8) uses Evaluate and not Select, but the result is not the attribute node but the element. Am I missing something?

**Comment by zhengchun** [comment]
The `/foo/bar@attr` change to `/foo/bar/@attr`, I think expression `/foo/bar@attr` and `/foo/bar/@attr` is different results.

```go
expr, _ := xpath.Compile("//foo/bar/@attr")
iter := expr.Evaluate(xmlquery.CreateXPathNavigator(doc))
switch typ := iter.(type) {
case *xpath.NodeIterator:
	for typ.MoveNext() {
		fmt.Printf("%v:%s\n", typ.Current().NodeType(), typ.Current().LocalName())
	}
}
```

**Comment by mildred** [comment]
Good to know. Then the question is which behaviour confirms with the [XPath W3C recommendation](https://www.w3.org/TR/xpath/). Do you have a goal to follow the recommendation closely or not?

When looking through the recommendation, the only occurence of `node/@attr` is for `../@attr`. It seems for non parent elements, they use `elem@attr` directly.

**Comment by zhengchun** [comment]
I'm test `foo/bar@attr` expression on [xpath-tester](https://www.freeformatter.com/xpath-tester.html), got  parse error:  
`Unable to parse any XML input. Unexpected token "@" beyond end of expression`

This error also occurs on .NET when using XML library.

So the `elem@attr` looks is not correct syntax.  xpath package should be return error when parsing this expression, but it not.

**Comment by mildred** [comment]
You are completely right, and I apologize for the issue that is not an issue. I tested this expression somewhere and I assumed that because it worked there, it was valid XPath.
