### ISSUE TITLE
Can you give some examples of usage of node axes? ex:getting the matching values of previous sibling and next sibling

### ISSUE THREAD

**Issue by ankalasravya** [antchfx/xpath#91]

**Comment by zhengchun** [comment]
for previous:

https://github.com/antchfx/xpath/blob/588960cceeace49841c2669e17a7a51f891e541b/xpath_test.go#L221

for next sibling:

https://github.com/antchfx/xpath/blob/588960cceeace49841c2669e17a7a51f891e541b/xpath_test.go#L207

for example:

`//div[@id='1']/following-sibling::div[@id='2']`
